//created by Clayton Tolotti: claytontolotti@gmail.com, on: 01/04/2018
package br.upf.protegemed.rules

import br.upf.protegemed.utils.Utils;
import br.upf.protegemed.beans.CapturaAtual;
import br.upf.protegemed.beans.ResultadoCalculoPericulosicade;
/*
rule "Rule Slinding Window"
	when
		$Captura : CapturaAtual( getEventos().getCodEvento() != null ) over window:time(5s)
	then
		Utils.logger("<<<<<<<<< Captura " + $Captura.getVm2() + " "
			+ drools.getRule().getName() + ">>>>>>>>>");
end

rule "Detect Event"
	when
		$status : CapturaAtual(  getCodCaptura() == null )
	then
		Utils.logger(drools.getRule().getName());
end

rule "Status Periculosidade"
	when
		$periculosidade : ResultadoCalculoPericulosicade (getResultado() != null)
	then
		Utils.logger(drools.getRule().getName() + " " + $periculosidade.getResultado());
end

rule "Detecte Similaridade Event"
	when
		$one : CapturaAtual( $evento : getEventos().getCodEvento() )
		$two : CapturaAtual( this.getEventos().getCodEvento() != $evento,
			this after[0s, 4s] $one)
	then
		Utils.logger(drools.getRule().getName() + " " + $evento + " != " + $two.getEventos().getCodEvento()) ;
		delete($one);
end

//this.getEquipamento().getRfid() != $rfid 
/*
rule "Detecte RFID diference with Events"
	when
		$capRfid : CapturaAtual( $rfid : getEquipamento().getRfid())
		//$capEvento : CapturaAtual( $evento : getEventos().getCodEvento() )
		$capEqui : CapturaAtual(this during[0s, 5s] $capRfid && this.getEquipamento().getRfid() != $rfid)
	then
		Utils.logger(drools.getRule().getName() + " " + $rfid + " != " + $capEqui.getEquipamento().getRfid());
	
end

rule "SEM Similaridade"
	when
		$one : CapturaAtual( $evento : getEventos().getCodEvento() ) 
		$two : CapturaAtual( this.getEventos().getCodEvento() == $evento,
			this coincides[0s, 10s] $one)
	then
		Utils.logger(drools.getRule().getName() + " " + $evento + " == " + $two.getEventos().getCodEvento()) ;
end
*/