//created by Clayton Tolotti: claytontolotti@gmail.com, on: 01/04/2018
package br.upf.protegemed.rules

import br.upf.protegemed.utils.Utils;
import br.upf.protegemed.beans.CapturaAtual;

rule "detect-flight-plug-one-six"
	when
		$eventOne : CapturaAtual( getEventos().getCodEvento() == 1 )
		$eventSix : CapturaAtual( getEventos().getCodEvento() == 6 )
		$outlet   : CapturaAtual(
						$eventSix.getTomada().getCodTomada() == $eventOne.getTomada().getCodTomada() 
						&& $eventSix after[0s] $eventOne
					)
		//$e : CapturaAtual( $e.calculaPericulosidade() > 0 )
	then
		Utils.logger(drools.getRule().getName() + " " + $outlet.durationBetweenEvent(
			$eventSix.getData(), $eventOne.getData()) + " tomada " + $eventOne.getTomada().getCodTomada());
		retract($eventSix);
		retract($eventOne);
end