//created by Clayton Tolotti: claytontolotti@gmail.com, on: 25/08/2018
package br.upf.protegemed.rules

import br.upf.protegemed.utils.Utils
import br.upf.protegemed.beans.eventos.PericulosidadeFugaEvento
import br.upf.protegemed.beans.eventos.ProcessarEventos

rule "rule-calculation-similaridade"
	salience 1
    when
    	$periculosidade : PericulosidadeFugaEvento( this.getTipo().equals("similaridade"))
    then
        Utils.logger("type -> " + $periculosidade.getTipo() +
        " resultado " + $periculosidade.getResultado() +
        " quantidade " + $periculosidade.getListCapturaAtual().size());
        if($periculosidade.getResultado() == 3.0){
        	Utils.logger("perigoso");
        	ProcessarEventos $processar = new ProcessarEventos(0);
			insert($processar);
        } else {
        	Utils.logger("nao perigoso");
			ProcessarEventos $processar = new ProcessarEventos(1);
			insert($processar);
			retract($periculosidade);
      	}
end