//created by Clayton Tolotti: claytontolotti@gmail.com on: 16/06/2018
package br.upf.protegemed.rules

import br.upf.protegemed.utils.Utils;
import br.upf.protegemed.beans.CapturaAtual;
import br.upf.protegemed.funcoes.FrequenciaCorrente;

rule "rule-frequencia-corrente"
	salience 5
    when
		$captura : CapturaAtual(  )
    then
		Utils.logger("frequencia via rule " + FrequenciaCorrente.getStatusFrequencia($captura));
end