//created by Clayton Tolotti: claytontolotti@gmail.com on: 15/06/2018
package br.upf.protegemed.rules

import br.upf.protegemed.utils.Utils;
import br.upf.protegemed.beans.CapturaAtual;
import br.upf.protegemed.dao.EscalaCorrenteDAO;
import br.upf.protegemed.dao.CapturaAtualDAO
import br.upf.protegemed.beans.escala.EscalaCorrente

rule "rule-calcule-corrente"
	salience 6
    when
        $captura : CapturaAtual(
					getEventos().getCodEvento() == 1
				)
    then
    	Integer $pericCorrente = EscalaCorrente.getStatusCorrente($captura);
    	new CapturaAtualDAO().updateCorrente($captura, $pericCorrente);
end
