//created by Clayton Tolotti: claytontolotti@gmail.com, on: 24/06/2018
package br.upf.protegemed.rules

import br.upf.protegemed.utils.Utils;
import br.upf.protegemed.beans.CapturaAtual;
import br.upf.protegemed.utils.Calculos;

rule "rule-calculate-similaridade"
	salience 4
    when
		$eventOneBefore : CapturaAtual( getEventos().getCodEvento() == 1) 
		$eventOneAfter : CapturaAtual( this.getEventos().getCodEvento() == 1
					&& this.getTomada().getCodTomada() != $eventOneBefore.getTomada().getCodTomada()
					&& this.getSalaCirurgia().getCodSala() == $eventOneBefore.getSalaCirurgia().getCodSala()
				)
    then
    	Calculos.calcularSpearman($eventOneBefore, $eventOneAfter);
end
