package br.upf.protegemed.rules
 
import br.upf.protegemed.utils.Utils;
import br.upf.protegemed.beans.CapturaAtual;
import br.upf.protegemed.beans.Eventos;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
 
rule "Teste"
    when
        m : CapturaAtual( getCodCaptura() == 2736,myMessage : "Executou regra " )
    then
        Utils.logger(myMessage + drools.getRule().getName());
end

rule "Vm_Com_Fuga"
	when
		captura : CapturaAtual( getVm2() != null )
	then
		Utils.logger(drools.getRule().getName() + " " + captura.getVm2());
end
		
		
		
		
		